#!/bin/bash

# Quick Setup Helper - Edit .env.local with your credentials

echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 ENVIRONMENT VARIABLES SETUP"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "✅ .env.local created with placeholders"
echo "✅ NEXTAUTH_SECRET generated: +yD1fdZZW/4Xjgg0hwbN3cG8/QHUTFa4nELhL07P0C4="
echo ""
echo "🔴 CRITICAL - You MUST update these values:"
echo ""
echo "1️⃣  DATABASE_URL"
echo "   📍 Supabase Dashboard → Settings → Database → Connection string"
echo "   ⚡ Choose: Transaction Mode (not Session Mode)"
echo "   📋 Format: postgresql://postgres.[REF]:[PASSWORD]@...pooler.supabase.com:6543/postgres"
echo ""
echo "2️⃣  SUPABASE_KEYS"
echo "   📍 Supabase Dashboard → Settings → API"
echo "   • NEXT_PUBLIC_SUPABASE_URL"
echo "   • NEXT_PUBLIC_SUPABASE_ANON_KEY"
echo "   • SUPABASE_SERVICE_ROLE_KEY"
echo ""
echo "3️⃣  STRIPE_KEYS (for payments)"
echo "   📍 https://dashboard.stripe.com/test/apikeys"
echo "   • STRIPE_SECRET_KEY=sk_test_..."
echo "   • STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo "   • NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY=pk_test_..."
echo ""
echo "4️⃣  MEDICI_TOKEN (for hotel bookings)"
echo "   • MEDICI_TOKEN=your_token"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "📝 Edit now: code .env.local"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "After updating .env.local, run:"
echo "  ./setup-database.sh    # Setup database"
echo "  npm run dev            # Start dev server"
echo ""
