import type { HotelSearchResult } from "@/lib/api/medici-types"

export const MOCK_HOTELS: HotelSearchResult[] = [
  {
  },
  {
    hotelId: 850086,
    hotelName: "Dave Gordon TLV",
    hotelImage: "/scarlet-hotel-main.jpg",
    images: ["/scarlet-hotel-lobby.jpg", "/scarlet-hotel-room.jpg", "/scarlet-hotel-bathroom.jpg"],
    location: "Dizengoff Street, Tel Aviv",
    city: "Tel Aviv",
    stars: 4,
    address: "123 Dizengoff St, Tel Aviv",
    description: "מלון בוטיק רומנטי במרכז תל אביב. חדרים מעוצבים בעיצוב עדכני, רחוק מחול כנס וברים.",
    facilities: ["WiFi חינם", "מטבח אורחים", "טראס מקורה", "אופניים"],
    rooms: [
      {
        code: "SCARLET_DELUXE_001",
        roomId: "12466-1",
        roomName: "Deluxe Double",
        roomCategory: "Deluxe",
        categoryId: 3,
        roomImage: "/scarlet-deluxe.jpg",
        images: [],
        bedding: "מיטה זוגית King",
        board: "חדר בלבד",
        boardId: 1,
        boardType: "RO",
        maxOccupancy: 2,
        size: 28,
        view: "נוף לעיר",
        amenities: ["מזגן", "טלוויזיה", "מיני בר", "שירותים יוקרתיים"],
        price: 650,
        buyPrice: 650,
        originalPrice: 850,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 24 שעות לפני ההגעה",
        available: 3,
      },
      {
        code: "SCARLET_GARDEN_002",
        roomId: "12466-2",
        roomName: "Garden Room with Terrace",
        roomCategory: "Superior",
        categoryId: 2,
        roomImage: "/scarlet-garden.jpg",
        images: [],
        bedding: "מיטה זוגית Queen",
        board: "לינה וארוחת בוקר",
        boardId: 2,
        boardType: "BB",
        maxOccupancy: 2,
        size: 32,
        view: "נוף לגן",
        amenities: ["מזגן", "טלוויזיה חכמה", "מטבחון", "טראס"],
        price: 750,
        buyPrice: 750,
        originalPrice: 950,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 48 שעות לפני ההגעה",
        available: 2,
      },
      {
        code: "SCARLET_SUITE_003",
        roomId: "12466-3",
        roomName: "Romantic Suite",
        roomCategory: "Suite",
        categoryId: 4,
        roomImage: "/scarlet-suite.jpg",
        images: [],
        bedding: "מיטה זוגית King + ספה",
        board: "לינה וארוחת בוקר",
        boardId: 2,
        boardType: "BB",
        maxOccupancy: 2,
        size: 45,
        view: "נוף פנורמי",
        amenities: ["מזגן", "ג'קוזי", "טלוויזיה חכמה", "מטבחון מלא", "שינייה"],
        price: 1050,
        buyPrice: 1050,
        originalPrice: 1350,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 72 שעות לפני ההגעה",
        available: 1,
      },
    ],
  },
  {
    hotelId: 1001,
    hotelName: "Royal Beach Tel Aviv",
    hotelName: "Royal Beach Tel Aviv",
    hotelImage: "/luxury-beach-hotel-tel-aviv.jpg",
    images: ["/luxury-hotel-lobby.png", "/hotel-pool-sunset.jpg", "/hotel-spa-relaxation.png"],
    location: "Herbert Samuel Promenade",
    city: "Tel Aviv",
    stars: 5,
    address: "19 Herbert Samuel St, Tel Aviv",
    description: "מלון בוטיק יוקרתי על חוף הים התיכון בלב תל אביב. חדרים מעוצבים, ספא מפנק ומסעדה גורמה.",
    facilities: ["WiFi חינם", "בריכה", "ספא", "מסעדה", "חניה", "חדר כושר"],
    rooms: [
      {
        code: "ROYAL_DELUXE_001",
        roomId: "101",
        roomName: "חדר דלוקס עם נוף לים",
        roomCategory: "Deluxe",
        categoryId: 3,
        roomImage: "/deluxe-hotel-room-sea-view.jpg",
        images: [],
        bedding: "מיטה זוגית King",
        board: "חדר בלבד",
        boardId: 1,
        boardType: "RO",
        maxOccupancy: 2,
        size: 35,
        view: "נוף לים",
        amenities: ["מזגן", "טלוויזיה", "מיני בר", "מרפסת"],
        price: 1200,
        buyPrice: 1200,
        originalPrice: 1500,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 24 שעות לפני ההגעה",
        available: 3,
      },
      {
        code: "ROYAL_SUITE_002",
        roomId: "102",
        roomName: "סוויטה רויאל עם ג'קוזי",
        roomCategory: "Suite",
        categoryId: 4,
        roomImage: "/luxury-hotel-suite-jacuzzi.jpg",
        images: [],
        bedding: "מיטה זוגית King + ספה",
        board: "לינה וארוחת בוקר",
        boardId: 2,
        boardType: "BB",
        maxOccupancy: 4,
        size: 60,
        view: "נוף פנורמי לים",
        amenities: ["מזגן", "טלוויזיה", "מיני בר", "מרפסת", "ג'קוזי", "סלון"],
        price: 2400,
        buyPrice: 2400,
        originalPrice: 3000,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 48 שעות לפני ההגעה",
        available: 2,
      },
    ],
    requestJson: '{"demo":"true"}',
    responseJson: {},
  },
  {
    hotelId: 1002,
    hotelName: "David Tower Jerusalem",
    hotelImage: "/luxury-hotel-jerusalem.jpg",
    images: ["/jerusalem-hotel-night.jpg", "/luxury-hotel-restaurant.png"],
    location: "King David Street",
    city: "Jerusalem",
    stars: 5,
    address: "23 King David St, Jerusalem",
    description: "מלון אייקוני בלב ירושלים עם נוף למזרח התיכון. שילוב מושלם של מסורת ויוקרה מודרנית.",
    facilities: ["WiFi חינם", "בריכה מקורה", "ספא", "3 מסעדות", "חניה", "חדר כושר", "גינה"],
    rooms: [
      {
        code: "DAVID_CLASSIC_001",
        roomId: "201",
        roomName: "חדר קלאסי",
        roomCategory: "Standard",
        categoryId: 1,
        roomImage: "/classic-hotel-room.jpg",
        images: [],
        bedding: "2 מיטות יחיד",
        board: "חדר בלבד",
        boardId: 1,
        boardType: "RO",
        maxOccupancy: 2,
        size: 28,
        view: "נוף לעיר",
        amenities: ["מזגן", "טלוויזיה", "מיני בר", "כספת"],
        price: 950,
        buyPrice: 950,
        originalPrice: 1200,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 24 שעות לפני ההגעה",
        available: 5,
      },
    ],
  },
  {
    hotelId: 1003,
    hotelName: "Carmel Forest Spa Resort",
    hotelImage: "/spa-resort-forest.jpg",
    images: [],
    location: "Carmel Mountains",
    city: "Haifa",
    stars: 5,
    address: "Carmel Forest, Haifa",
    description: "אתר נופש יוקרתי ביער הכרמל. מושלם לבריחה רומנטית או חופשה משפחתית מרעננת.",
    facilities: ["WiFi חינם", "ספא מלא", "בריכות מחוממות", "מסעדה אורגנית", "חניה", "טיולי טבע"],
    rooms: [
      {
        code: "CARMEL_FOREST_001",
        roomId: "301",
        roomName: "בקתה ביער",
        roomCategory: "Superior",
        categoryId: 2,
        roomImage: "/forest-cabin-room.jpg",
        images: [],
        bedding: "מיטה זוגית Queen",
        board: "חצי פנסיון",
        boardId: 3,
        boardType: "HB",
        maxOccupancy: 2,
        size: 40,
        view: "נוף ליער",
        amenities: ["מזגן", "קמין", "מרפסת פרטית", "אמבט גדול"],
        price: 1800,
        buyPrice: 1800,
        originalPrice: 2200,
        currency: "ILS",
        cancellationPolicy: "ביטול חינם עד 72 שעות לפני ההגעה",
        available: 4,
      },
    ],
  },
]
