import type { Hotel, Room, RatePlan } from "@/types/booking"

export const mockHotel: Hotel = {
  id: "hotel-1",
  name: "The Grand Azure Hotel",
  slug: "grand-azure",
  description:
    "Experience luxury at its finest in the heart of Tel Aviv. Our 5-star hotel offers breathtaking Mediterranean views, world-class amenities, and unparalleled service.",
  address: "Herbert Samuel St 14",
  city: "Tel Aviv",
  country: "Israel",
  stars: 5,
  images: ["/luxury-hotel-lobby-with-chandeliers.jpg", "/hotel-rooftop-pool-ocean-view.jpg", "/elegant-hotel-restaurant.jpg"],
  amenities: [
    "Free WiFi",
    "Pool",
    "Spa",
    "Fitness Center",
    "Restaurant",
    "Bar",
    "Room Service",
    "Parking",
    "Beach Access",
  ],
  policies: {
    checkIn: "15:00",
    checkOut: "11:00",
    cancellation: "Free cancellation up to 24 hours before check-in",
  },
  currency: "ILS",
  primaryColor: "#1e3a5f",
}

export const mockRooms: Room[] = [
  {
    id: "room-1",
    hotelId: "hotel-1",
    name: "Deluxe Sea View Room",
    description:
      "Spacious room with stunning Mediterranean Sea views, featuring a king-size bed, marble bathroom, and private balcony.",
    images: ["/luxury-hotel-room-sea-view-king-bed.jpg", "/modern-hotel-bathroom-marble.jpg", "/hotel-room-balcony-sea-view.jpg"],
    maxGuests: 3,
    maxAdults: 2,
    maxChildren: 1,
    bedType: "King Bed",
    size: 45,
    amenities: ["Sea View", "Balcony", "Mini Bar", "Safe", "Air Conditioning", "Flat Screen TV", "Coffee Machine"],
    basePrice: 850,
    available: 5,
  },
  {
    id: "room-2",
    hotelId: "hotel-1",
    name: "Premium Suite",
    description:
      "Luxurious suite with separate living area, panoramic views, and exclusive access to the Executive Lounge.",
    images: ["/luxury-hotel-suite-living-room-modern.jpg", "/hotel-suite-bedroom-elegant.jpg", "/luxury-bathroom-jacuzzi.jpg"],
    maxGuests: 4,
    maxAdults: 2,
    maxChildren: 2,
    bedType: "King Bed + Sofa Bed",
    size: 75,
    amenities: [
      "Panoramic View",
      "Living Room",
      "Jacuzzi",
      "Executive Lounge Access",
      "Butler Service",
      "Nespresso Machine",
    ],
    basePrice: 1450,
    available: 3,
  },
  {
    id: "room-3",
    hotelId: "hotel-1",
    name: "Classic City View Room",
    description: "Comfortable room with city views, perfect for business travelers and couples seeking a cozy retreat.",
    images: ["/hotel-room-city-view-modern.jpg", "/hotel-bathroom-clean-modern.jpg"],
    maxGuests: 2,
    maxAdults: 2,
    maxChildren: 0,
    bedType: "Queen Bed",
    size: 32,
    amenities: ["City View", "Work Desk", "Mini Bar", "Safe", "Air Conditioning", "Flat Screen TV"],
    basePrice: 550,
    available: 8,
  },
  {
    id: "room-4",
    hotelId: "hotel-1",
    name: "Family Suite",
    description: "Spacious two-bedroom suite ideal for families, featuring a kitchenette and connecting rooms.",
    images: ["/hotel-family-suite-two-beds.jpg", "/hotel-kitchenette-modern.jpg", "/hotel-kids-room-colorful.jpg"],
    maxGuests: 6,
    maxAdults: 4,
    maxChildren: 4,
    bedType: "2 Queen Beds + 2 Single Beds",
    size: 95,
    amenities: ["Two Bedrooms", "Kitchenette", "Living Room", "Kids Amenities", "Game Console", "Washing Machine"],
    basePrice: 1850,
    available: 2,
  },
]

export const mockRatePlans: RatePlan[] = [
  // Deluxe Sea View Room
  {
    id: "rate-1-1",
    roomId: "room-1",
    name: "Best Available Rate",
    description: "Our best flexible rate with free cancellation",
    price: 850,
    includes: ["Free WiFi", "Access to Fitness Center"],
    cancellationPolicy: "free",
    prepayment: "none",
    mealPlan: "room-only",
  },
  {
    id: "rate-1-2",
    roomId: "room-1",
    name: "Bed & Breakfast",
    description: "Start your day with our gourmet breakfast buffet",
    price: 950,
    includes: ["Breakfast Buffet", "Free WiFi", "Access to Fitness Center"],
    cancellationPolicy: "free",
    prepayment: "none",
    mealPlan: "breakfast",
  },
  {
    id: "rate-1-3",
    roomId: "room-1",
    name: "Non-Refundable Saver",
    description: "Best price - non-refundable",
    price: 720,
    originalPrice: 850,
    includes: ["Free WiFi", "Access to Fitness Center"],
    cancellationPolicy: "non-refundable",
    prepayment: "full",
    mealPlan: "room-only",
  },
  // Premium Suite
  {
    id: "rate-2-1",
    roomId: "room-2",
    name: "Suite Experience",
    description: "Full suite experience with all amenities",
    price: 1450,
    includes: ["Breakfast", "Executive Lounge", "Spa Credit ₪200", "Late Checkout"],
    cancellationPolicy: "free",
    prepayment: "partial",
    mealPlan: "breakfast",
  },
  {
    id: "rate-2-2",
    roomId: "room-2",
    name: "Half Board Package",
    description: "Breakfast and dinner included",
    price: 1750,
    includes: ["Breakfast & Dinner", "Executive Lounge", "Spa Credit ₪300", "Late Checkout"],
    cancellationPolicy: "free",
    prepayment: "partial",
    mealPlan: "half-board",
  },
  // Classic City View
  {
    id: "rate-3-1",
    roomId: "room-3",
    name: "Room Only",
    description: "Simple and affordable",
    price: 550,
    includes: ["Free WiFi"],
    cancellationPolicy: "free",
    prepayment: "none",
    mealPlan: "room-only",
  },
  {
    id: "rate-3-2",
    roomId: "room-3",
    name: "With Breakfast",
    description: "Including breakfast buffet",
    price: 650,
    includes: ["Breakfast Buffet", "Free WiFi"],
    cancellationPolicy: "free",
    prepayment: "none",
    mealPlan: "breakfast",
  },
  // Family Suite
  {
    id: "rate-4-1",
    roomId: "room-4",
    name: "Family Package",
    description: "Perfect for families with kids activities included",
    price: 1850,
    includes: ["Breakfast for all", "Kids Club Access", "Welcome Gift for Kids"],
    cancellationPolicy: "free",
    prepayment: "partial",
    mealPlan: "breakfast",
  },
  {
    id: "rate-4-2",
    roomId: "room-4",
    name: "All-Inclusive Family",
    description: "Everything included for a worry-free vacation",
    price: 2450,
    includes: ["All Meals", "Kids Club", "Mini Bar", "Room Service", "Spa Access"],
    cancellationPolicy: "partial",
    prepayment: "partial",
    mealPlan: "all-inclusive",
  },
]

export function getRoomRatePlans(roomId: string): RatePlan[] {
  return mockRatePlans.filter((rp) => rp.roomId === roomId)
}
